//! Gzip the checked-in `data/oui.tsv` into `OUT_DIR` at build time so `oui.rs`
//! can embed the ~555 KB compressed blob instead of the ~1.8 MB raw table. The
//! plain `.tsv` stays in the repo as the human-readable, greppable source of
//! truth (regenerated by `examples/gen_oui.rs`); only the binary ships
//! compressed, decompressed once on first lookup.

use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=data/oui.tsv");

    let src = std::fs::read("data/oui.tsv").expect("read data/oui.tsv");
    let out = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("oui.tsv.gz");

    let file = std::fs::File::create(&out).expect("create oui.tsv.gz");
    let mut encoder = flate2::write::GzEncoder::new(file, flate2::Compression::best());
    encoder.write_all(&src).expect("gzip oui.tsv");
    encoder.finish().expect("finish gzip");
}
